# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ef88cbb7202dec6a1e0f1e901c630b8f9318a1e34d0560797e146f675444ccbffbc5133c86eae61740c2c65daa393e0e2fb61de68d505e382f11b17a06d73a5

test:
  secret_key_base: c19b3f8e34763ac3cb859c82f45562d5c2f3bf0df0300579a91a17f9e2a6d51fd0fba0793dfa5240abd394b38a8b122bb75268ce922dd605910782dc4613f3fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
